[utility]
    controllers="./controllers.py"

    [utility.volume]
    param="%controllers"
    msg="bruh"
    bind="SHIFT"

    [utility.dec]
    param="bean %controllers"
    msg="deca "
    bind="SHIFT"

    [utility.volume.keen]
    controllers="1"
    param="%controllers $[1,2,3]"
    msg="bruh $[1,2,3]"
    bind="SHIFT"


